name: bloc_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter dependencies
  cupertino_icons: ^1.0.8

  # BLoC and state management
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  equatable: ^2.0.0

  # UI packages
  gradient_borders: ^1.0.1
  flutter_screenutil: ^5.9.3
  pin_code_fields: ^8.0.1
  google_nav_bar: ^5.0.7
  country_code_picker: ^3.3.0
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  simple_gradient_text: ^1.3.0
  fluttertoast: ^8.2.4

  # Storage and preferences
  get: ^4.7.2
  get_storage: ^2.1.1
  shared_preferences: ^2.5.3

  # Networking
  http: ^1.2.0
  intl: ^0.20.2

  # Media handling
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  video_player: ^2.10.0
  better_player_plus: ^1.0.8
  # better_player: ^0.0.84

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
